### ISSUE TITLE
RMG Database Editor not present

### ISSUE THREAD

**Issue by DetlevCM** [GreenGroup/RMG-Java#309]
In RMG 4.0.1 and in the developmen code I cannot see the database editor referenced in the manual.

What happened to it?

**Comment by rwest** [comment]
I think it was (unintentionally) omitted from that release package. Probably because it's not part of the development code here on github. You may be able to find it in a previous release package on sourceforge (if so, please report back here!)

**Comment by DetlevCM** [comment]
Ah, that explains it - I checked up on it and both the code and the binaries are present in RMG 3.3
http://sourceforge.net/projects/rmg/files/rmg/

Guess this can be closed? (And you might want to consider including the tool again if it remains in the manual.)
